### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by hectorespert**
Update project to use in Elgg 2.3.
Allow dowload with composer and get  PHPmailer lib with composer

### CODE REVIEW

**Comment by cash** [comment]
Thanks for the pull request. Could you remove the netbeans specific files and add those to the .gitignore?

**Comment by hectorespert** [comment]
@cash I removed the netbeans specific files

**Comment by cash** [comment]
Are additional instructions needed in the readme to explain how to install plugin when using composer (I haven't used Elgg since they added support for composer)?

**Comment by hectorespert** [comment]
@cash Have you a [packagist](https://packagist.org/) account to distribute the package with composer?

**Comment by cash** [comment]
@blackleg yes, I have a packagist account.

**Comment by cash** [comment]
The username is cash. I can update the composer file and submit. I'll probably call the page cash/elgg-phpmailer rather than just cash/phpmailer to avoid the impression it is a version of the library.

**Comment by hectorespert** [comment]
To use the plugin with composer, you only need install the plugin with composer:

```bash
composer require cash/elgg-phpmailer
```

The composer/installer package install the plugin in the elgg mod folder.

**Comment by hectorespert** [comment]
I updated the README with the instructions needed to install the package

**Comment by hectorespert** [comment]
@cash Thanks for accept my pull request. Can you submit the package to packagist to start using the last commits?

**Comment by cash** [comment]
It should be available now.

**Comment by hectorespert** [comment]
Thanks

**Pull request merged**
